DROP TABLE IF EXISTS ta_person;

CREATE TABLE ta_person
  (
    id INT NOT NULL AUTO_INCREMENT,
    email VARCHAR(50) NOT NULL,
    name VARCHAR(50) NOT NULL,
    sex BIT NOT NULL,
    phone VARCHAR(50) NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;